package egoproj_nb;

import java.sql.Connection;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class FrmGiris extends javax.swing.JFrame {

    /**
     * Creates new form FrmGiris
     */
    public FrmGiris() {
        initComponents();
        PgConnector pgc =new PgConnector();
        Connection c = pgc.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        btnYakınDurak = new javax.swing.JButton();
        txtOtobus = new javax.swing.JTextField();
        btnDuyurular = new javax.swing.JButton();
        btnDurakAra = new javax.swing.JButton();
        btnHatlar = new javax.swing.JButton();
        btnAnkarakart = new javax.swing.JButton();
        btnBildir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EGO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnYakınDurak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/yakınduraklar.png"))); // NOI18N
        btnYakınDurak.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/image/bg_grad.jpg")))); // NOI18N
        btnYakınDurak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYakınDurakActionPerformed(evt);
            }
        });
        getContentPane().add(btnYakınDurak, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 120, 90));

        txtOtobus.setToolTipText("Otobüs Nerede ?");
        txtOtobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtobusActionPerformed(evt);
            }
        });
        getContentPane().add(txtOtobus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 305, -1));

        btnDuyurular.setBackground(new java.awt.Color(255, 255, 255));
        btnDuyurular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/duyurular.png"))); // NOI18N
        btnDuyurular.setToolTipText("");
        btnDuyurular.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/image/bg_grad.jpg")))); // NOI18N
        btnDuyurular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyurularActionPerformed(evt);
            }
        });
        getContentPane().add(btnDuyurular, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 120, 90));

        btnDurakAra.setBackground(new java.awt.Color(255, 255, 255));
        btnDurakAra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/durakara.png"))); // NOI18N
        btnDurakAra.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/image/bg_grad.jpg")))); // NOI18N
        btnDurakAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDurakAraActionPerformed(evt);
            }
        });
        getContentPane().add(btnDurakAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 120, 90));

        btnHatlar.setBackground(new java.awt.Color(255, 255, 255));
        btnHatlar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hatveseferler.png"))); // NOI18N
        btnHatlar.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/image/bg_grad.jpg")))); // NOI18N
        btnHatlar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHatlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHatlarActionPerformed(evt);
            }
        });
        getContentPane().add(btnHatlar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 120, 90));

        btnAnkarakart.setBackground(new java.awt.Color(255, 255, 255));
        btnAnkarakart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ankarakart.png"))); // NOI18N
        btnAnkarakart.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/image/bg_grad.jpg")))); // NOI18N
        btnAnkarakart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnkarakartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnkarakart, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 120, 90));

        btnBildir.setBackground(new java.awt.Color(255, 255, 255));
        btnBildir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sorunbildir.png"))); // NOI18N
        btnBildir.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/image/bg_grad.jpg")))); // NOI18N
        btnBildir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBildirActionPerformed(evt);
            }
        });
        getContentPane().add(btnBildir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 120, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 1170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDuyurularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyurularActionPerformed
        // TODO add your handling code here:
        FrmDuyurular frm1=new FrmDuyurular();
        frm1.setVisible(true);
        frm1.parent=this;
        
    }//GEN-LAST:event_btnDuyurularActionPerformed

    private void txtOtobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtobusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtobusActionPerformed

    private void btnDurakAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDurakAraActionPerformed
        // TODO add your handling code here:
        
        FrmDurakAra frm2=new FrmDurakAra();
        frm2.setVisible(true);
        frm2.parent=this;
        
    }//GEN-LAST:event_btnDurakAraActionPerformed

    private void btnBildirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBildirActionPerformed
        // TODO add your handling code here:
        
        FrmBildir frm6=new FrmBildir();
        frm6.setVisible(true);
        frm6.parent=this;
    }//GEN-LAST:event_btnBildirActionPerformed

    private void btnHatlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHatlarActionPerformed
        // TODO add your handling code here:
        FrmHatlar frm3=new FrmHatlar();
        frm3.setVisible(true);
        frm3.parent=this;
    }//GEN-LAST:event_btnHatlarActionPerformed

    private void btnYakınDurakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYakınDurakActionPerformed
        // TODO add your handling code here:
        
        Harita frm5=new Harita();
        frm5.setVisible(true);
        frm5.parent=this;
    }//GEN-LAST:event_btnYakınDurakActionPerformed

    private void btnAnkarakartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnkarakartActionPerformed
        // TODO add your handling code here:
        
        BHarita frm4=new BHarita();
        frm4.setVisible(true);
        frm4.parent=this;
    }//GEN-LAST:event_btnAnkarakartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnkarakart;
    private javax.swing.JButton btnBildir;
    private javax.swing.JButton btnDurakAra;
    private javax.swing.JButton btnDuyurular;
    private javax.swing.JButton btnHatlar;
    private javax.swing.JButton btnYakınDurak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField txtOtobus;
    // End of variables declaration//GEN-END:variables
}
