/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package egoproj_nb;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FrmHatlar extends javax.swing.JFrame {

    public FrmGiris parent;
    
    String sorgu;
    DefaultTableModel modelim = new DefaultTableModel();
    Object[] kolonlar ={"Hat Numarası","Hat Adı"};
    Object[] satirlar=new Object[2];
    public FrmHatlar() {
        initComponents();
        otobusGetir();
    }
    
    private void otobusGetir() {
        
        PgConnector pgc =new PgConnector();
        Connection c = pgc.getConnection();
        
        String sorgu = "SELECT hat_no, hat_adi FROM public.t_otobus";
        modelim.setColumnCount(0);
        modelim.setRowCount(0);
        modelim.setColumnIdentifiers(kolonlar);
        
        ResultSet rs = PgConnector.listele(sorgu);
        try {
            while (rs.next()) {                
                satirlar[0]=rs.getInt("hat_no");   
                satirlar[1]=rs.getString("hat_adi");
                modelim.addRow(satirlar);
            }
            jTable2.setModel(modelim);
            
        } catch (SQLException sQLException) {
        }
    }
    private void otobusBul() {
        
        PgConnector pgc =new PgConnector();
        Connection c = pgc.getConnection();
        String hn= txtOAra.getText();
        String sorgu = "SELECT hat_no, hat_adi FROM public.t_otobus WHERE hat_no='"+hn+"'";
        
        modelim.setColumnCount(0);
        modelim.setRowCount(0);
        modelim.setColumnIdentifiers(kolonlar);
        
        ResultSet rs = PgConnector.listele(sorgu);
        
        try {
            while (rs.next()) {                
                satirlar[0]=rs.getInt("hat_no");   
                satirlar[1]=rs.getString("hat_adi");
                modelim.addRow(satirlar);

            }
            jTable2.setModel(modelim);

        } catch (SQLException sQLException) {

        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTable1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtOAra = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HATLAR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setViewportView(jTable2);

        getContentPane().add(jTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 510, 240));
        getContentPane().add(txtOAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 200, 30));

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 50, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_grad.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        otobusBul();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHatlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHatlar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtOAra;
    // End of variables declaration//GEN-END:variables
}
